language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g changelogger
install:
  - npm install
  - bower install
services:
  - mongodb
  - redis-server
notifications:
  email:
    - jfugett27@gmail.com